package org.soubao.starter.common;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import java.util.EnumSet;

/**
 * 业务返回枚举
 */
public enum ResultEnum {

    FAIL(-1,"fail"),
    NO_LOGIN_ERROR(-100, "please_login"),
    SUCCESS(1, "success"),
    UNKNOWN_ERROR(0, "unknown_error"),
    DATA_NOT_EXIST(-2, "DATA_NOT_EXIST"),

    INVALID_TOKEN(-10000, "INVALID_TOKEN"),
    WX_MINI_APP_LOGIN_ERROR(-10001, "WX_MINI_APP_LOGIN_ERROR"),
    NEED_BIND_ACCOUNT(-10002, "NEED_BIND_ACCOUNT"),
    NO_VERIFY_CODE(-10003, "NO_VERIFY_CODE"),
    VERIFY_CODE_TIME_OUT(-10004, "VERIFY_CODE_TIME_OUT"),
    VERIFY_CODE_ERROR(-10005, "VERIFY_CODE_ERROR"),
    LOGIN_ACCOUNT_EXIST(-10006, "LOGIN_ACCOUNT_EXIST"),
    ACCOUNT_EXISTS(-10007, "ACCOUNT_EXISTS"),
    GOODS_IS_NOT_SHIPPING(-10008, "GOODS_IS_NOT_SHIPPING"),
    STORE_COLLECT_EXISTS(-10009, "STORE_COLLECT_EXISTS"),
    LOGIN_ERROR(-10010, "LOGIN_ERROR"),
    ORDER_NOT_FINISH(-10011, "order_unfinished"),
    NEWS_EXISTS_CAN_NOT_REMOVE(-10012, "NEWS_EXISTS_CAN_NOT_REMOVE"),
    NO_CONFIG_FREIGHT(-10013, "no_freight_config"),
    TOO_MANY_ADDRESS(-10014, "too_many_address"),
    NOT_DISTRIBUTORS(-10015, "not_distributor"),
    GOODS_NOT_EXISTS(-10016, "GOODS_NOT_EXISTS"),
    STORE_NOT_EXISTS(-10017, "STORE_NOT_EXISTS"),
    WITHDRAWAL_DISABLE(-10018, "WITHDRAWAL_DISABLE"),
    FREEZING_OF_FUND(-10019, "FREEZING_OF_FUND"),
    PAYPWD_NOT_SET(-10020, "PAYPWD_NOT_SET"),
    NAME_EXISTS(-10021, "NAME_EXISTS"),
    NOT_SUFFICIENT_FUNDS(-10022, "NOT_SUFFICIENT_FUNDS"),
    MIN_CASH(-10023, "MIN_CASH"),
    MAX_CASH(-10024, "MAX_CASH"),
    MAX_WITHDRAWALS_COUNT(-10025, "MAX_WITHDRAWALS_COUNT"),
    WX_MINI_APP_NO_CONFIG_ERROR(-10026, "WX_MINI_APP_NO_CONFIG_ERROR"),
    TAXFEE_ERROR(-10027, "TAXFEE_ERROR"),
    NOT_BIND_MOBILE(-10028, "NOT_BIND_MOBILE"),
    PASSWORD_LENGTH_ERROR(-10029, "PASSWORD_LENGTH_ERROR"),
    OLD_PASSWORD_ERROR(-10030, "OLD_PASSWORD_ERROR"),
    MOBILE_IS_BINDING(-10031, "MOBILE_IS_BINDING"),
    SCENE_CODE_ERROR(-10032, "SCENE_CODE_ERROR"),
    EMAIL_IN_USE(-10033, "EMAIL_IN_USE"),
    ACTIVITY_NOT_EXISTS(-10034, "ACTIVITY_NOT_EXISTS"),
    ACTIVITY_TIME_IS_OVER(-10035, "ACTIVITY_TIME_IS_OVER"),
    COUPON_COUNT_ZERO(-10036, "COUPON_COUNT_ZERO"),
    USER_COUPON_EXISTS(-10037, "USER_COUPON_EXISTS"),
    PARAM_ERROR(-10038, "PARAM_ERROR"),
    COUPON_CODE_INVALID(-10039, "COUPON_CODE_INVALID"),
    COUPON_IS_USED(-10040, "COUPON_IS_USED"),
    COUPON_EXCHANGED(-10041, "COUPON_EXCHANGED"),
    COUPON_INVALID(-10042, "COUPON_INVALID"),
    STORE_NAME_EXISTS(-10043, "STORE_NAME_EXISTS"),
    STORE_CLASS_ERROR(-10045, "STORE_CLASS_ERROR"),
    ACCOUNT_NOT_EXISTS(-10046, "ACCOUNT_NOT_EXISTS"),
    ACCOUNT_IS_BINDIND(-10047, "ACCOUNT_IS_BINDIND"),
    MKDIR_ERROR(-10048, "MKDIR_ERROR"),
    IMAGE_TYPE_ERROR(-10049, "IMAGE_TYPE_ERROR"),
    UPLOAD_FAIL(-10050, "UPLOAD_FAIL"),
    COUPON_ILLEGAL(-10051, "COUPON_ILLEGAL"),
    THIRD_ACCOUNT_IS_BIND(-10052, "THIRD_ACCOUNT_IS_BIND"),
    ACTIVITY_CANNOT_DELETED(-10054, "ACTIVITY_CANNOT_DELETED"),
    SIGN_CONFIG_NO_ON(-10055, "SIGN_CONFIG_NO_ON"),
    SIGN_REPEAT(-10056, "SIGN_REPEAT"),
    ACTIVITY_CANNOT_BE_ADD(-10057, "ACTIVITY_CANNOT_BE_ADD"),
    FILE_FORMAT_ERROR(-10058, "FILE_FORMAT_ERROR"),
    DERIVED_ANOMALY(-10059, "DERIVED_ANOMALY"),
    EXCELTYPEENUM_CAN_NOT_NULL(-10060, "EXCELTYPEENUM_CAN_NOT_NULL"),
    SUBJECT_NAME_EXISTS(-10061, "SUBJECT_NAME_EXISTS"),
    WX_PAY_PRE_ERROR(-10062, "WX_PAY_PRE_ERROR"),
    WX_PAY_ERROR(-10063, "WX_PAY_ERROR"),
    REFUND_AMOUNT_ERROR(-10064, "REFUND_AMOUNT_ERROR"),
    ORDER_DELETED(-10065, "ORDER_DELETED"),
    ORDER_NOT_IS_INVALID(-10066, "ORDER_NOT_IS_INVALID"),
    NO_CONFIG_WS_PAY_HOST(-10067, "NO_CONFIG_WS_PAY_HOST"),
    NO_CONFIG_WS_PAY_CONFIG(-10068, "NO_CONFIG_WS_PAY_CONFIG"),
    ORDER_CANCEL_HAVE_RETURN_ERR(-10070, "ORDER_CANCEL_HAVE_RETURN_ERR"),
    ORDER_NOT_RECEIVE(-10071, "ORDER_NOT_RECEIVE"),
    ORDER_NOT_CANCEL(-10072, "ORDER_NOT_CANCEL"),
    ORDER_HAVE_COMMENT(-10073, "ORDER_HAVE_COMMENT"),
    ORDER_NOT_INVALID(-10074, "ORDER_NOT_INVALID"),
    ORDER_NOT_CONFIRM(-10075, "ORDER_NOT_CONFIRM"),
    ORDER_NOT_CANCEL_CONFIRM(-10076, "ORDER_NOT_CANCEL_CONFIRM"),
    ORDER_NOT_REFUND(-10078, "ORDER_NOT_REFUND"),
    ORDER_GOODS_ON_RETURN(-10079, "ORDER_GOODS_ON_RETURN"),
    ERROR_ORDER(-10080, "ERROR_ORDER"),
    ADD_SPEC_ERROR(-10081, "ADD_SPEC_ERROR"),
    NO_USE_MSG_REG(-10082, "NO_USE_MSG_REG"),
    NO_EXIST_SMS_TEMP(-10083, "NO_EXIST_SMS_TEMP"),
    NO_SUPPORT_TRADE_TYPE(-10084, "NO_SUPPORT_TRADE_TYPE"),
    ACCOUNT_PARAM_ERROR(-10085, "ACCOUNT_PARAM_ERROR"),
    MODIFY_ORDER_AMOUNT_NOT_ZERO(-10086, "MODIFY_ORDER_AMOUNT_NOT_ZERO"),
    MODIFY_DISTRIBUTION_NOT_ENOUGH(-10087, "MODIFY_DISTRIBUTION_NOT_ENOUGH"),
    REFUND_MONEY_MORE_THAN_PAY_MONEY(-10088, "REFUND_MONEY_MORE_THAN_PAY_MONEY"),
    NOT_AGREE_REFUND(-10089, "NOT_AGREE_REFUND"),
    NOT_RETURN_GOODS(-10090, "NOT_RETURN_GOODS"),
    SHIPPING_TEMPLATE_ERROR(-10091, "SHIPPING_TEMPLATE_ERROR"),
    COUPON_NUM_ERROR(-10092, "COUPON_NUM_ERROR"),
    START_TIME_GT_END_TIME(-10092, "START_TIME_GT_END_TIME"),
    SHIPPING_PLUG_IS_NOT_EXIST(-10093, "SHIPPING_PLUG_IS_NOT_EXIST"),
    NO_HAVE_MASTER_GOODS(-10094, "NO_HAVE_MASTER_GOODS"),
    UN_LESS_TWO_GOODS(-10095, "UN_LESS_TWO_GOODS"),
    COMBINATION_CANNOT_ON_SALE(-10096, "COMBINATION_CANNOT_ON_SALE"),
    COMBINATION_GOODS_HAVE_BEEN(-10097, "COMBINATION_GOODS_HAVE_BEEN"),
    ADD_USER_MONEY_ERROR(-10098, "ADD_USER_MONEY_ERROR"),
    ADD_USER_PAY_POINTS_ERROR(-10098, "ADD_USER_PAY_POINTS_ERROR"),
    ADD_USER_FROZEN_MONEY_ERROR(-10099, "ADD_USER_FROZEN_MONEY_ERROR"),
    UPLOAD_WX_IMG_MAX_SIZE_ERROR(-10100, "UPLOAD_WX_IMG_MAX_SIZE_ERROR"),
    FIRST_LEADER_NOT_EXISTS(-10101, "FIRST_LEADER_NOT_EXISTS"),
    CONDITIONS_DO_NOT_MATCH(-10102, "CONDITIONS_DO_NOT_MATCH"),
    ALREADY_YOUR_SUPERIOR(-10103, "ALREADY_YOUR_SUPERIOR"),
    CANNOT_RETURN_GOODS(-10104, "CANNOT_RETURN_GOODS"),
    CANNOT_COMPLAIN(-10105, "CANNOT_COMPLAIN"),
    COMPLAIN_HAVE_BENN_APPLY(-10106, "COMPLAIN_HAVE_BENN_APPLY"),
    GOODS_HAVE_BEEN_EXPOSE(-10107, "GOODS_HAVE_BEEN_EXPOSE"),
    VIDEO_TYPE_ERROR(-10108, "VIDEO_TYPE_ERROR"),
    FILE_TYPE_ERROR(-10110, "FILE_TYPE_ERROR"),

    UPLOAD_FAIL_OSS_ERROR(-15000, "UPLOAD_FAIL_OSS_ERROR"),

    CANNOT_EDIT_SYSTEM_ARTICLE_CAT(-20001, "CANNOT_EDIT_SYSTEM_ARTICLE_CAT"),
    CANNOT_REMOVE_SYSTEM_CAT(-20002, "CANNOT_REMOVE_SYSTEM_CAT"),
    CAT_HAVE_ARTICLE(-20003, "CAT_HAVE_ARTICLE"),
    PARENT_CANNOT_BE_HIMSELF(-20004, "PARENT_CANNOT_BE_HIMSELF"),
    DOC_CODE_EXISTS(-20005, "DOC_CODE_EXISTS"),
    NOT_SET_TO_CHILDREN(-20006, "NOT_SET_TO_CHILDREN"),
    HELP_TYPE_LEVEL_ERROR(-20007, "HELP_TYPE_LEVEL_ERROR"),
    HELP_TYPE_HAVE_HELP(-20008, "HELP_TYPE_HAVE_HELP"),
    HELP_TYPE_HAVE_CHILD(-20009, "HELP_TYPE_HAVE_CHILD"),
    GOODS_CATEGORY_LEVEL_ERROR(-20010, "GOODS_CATEGORY_LEVEL_ERROR"),
    STORE_GRADE_NOT_EXISTS(-20011, "STORE_GRADE_NOT_EXISTS"),
    RELEASE_GOODS_COUNT_MAX(-20012, "RELEASE_GOODS_COUNT_MAX"),
    STORE_GOODS_CLASS_LEVEL_ERROR(-20013, "STORE_GOODS_CLASS_LEVEL_ERROR"),

    ADD_CART_NO_GOODS(-40001, "ADD_CART_NO_GOODS"),
    ADD_CART_TOO_MANY(-40002, "ADD_CART_TOO_MANY"),
    ADD_CART_NO_SPEC(-40003, "ADD_CART_NO_SPEC"),
    NOT_ENOUGH_STOCK(-40004, "NOT_ENOUGH_STOCK"),
    LITTLE_ORDER_GOODS_NO_SHIPPING(-40005, "LITTLE_ORDER_GOODS_NO_SHIPPING"),
    USE_POINT_ERROR(-40006, "USE_POINT_ERROR"),
    NO_PAY_PWD_SETTING(-40007, "NO_PAY_PWD_SETTING"),
    NO_PAY_PWD(-40007, "NO_PAY_PWD"),
    INVALID_PAY_PWD(-40007, "INVALID_PAY_PWD"),
    NO_FIND_ORDER(-40008, "NO_FIND_ORDER"),
    USER_LOCK(-40009, "USER_LOCK"),
    PAY_PSW_ERROR(-40009, "PAY_PSW_ERROR"),
    NOT_ENOUGH_USER_MONEY(-40009, "NOT_ENOUGH_USER_MONEY"),
    ORDER_PAYED(-40009, "ORDER_PAYED"),
    LIMIT_NUM_ERROR(-40010, "LIMIT_NUM_ERROR"),
    ORDER_PAY_ERROR(-40012, "ORDER_PAY_ERROR"),
    TEAM_ORDER_EXPIRE_CANCLE(-40014, "TEAM_ORDER_EXPIRE_CANCLE"),
    USER_HAVE_STORE(-40101, "USER_HAVE_STORE"),
    NO_FIND_FOUND(-40102, "NO_FIND_FOUND"),
    FOUND_STATUS_IS_NO_ABLE(-40103, "FOUND_STATUS_IS_NO_ABLE"),
    NO_FIND_TEAM(-40104, "NO_FIND_TEAM~"),
    TEAM_STATUS_NO_WAY(-40105, "TEAM_STATUS_NO_WAY"),
    TEAM_TYPE_NO_WAY(-40106, "TEAM_TYPE_NO_WAY"),
    TEAM_HAD_LOTTERY(-40107, "TEAM_HAD_LOTTERY"),
    NO_FIND_SUCCESS_FOUND(-40108, "NO_FIND_SUCCESS_FOUND"),
    POST_CODE_NO_FOUND(-40108, "POST_CODE_DOES_NOT_EXIST"),

    CAT_HAVE_CHILD(-41001, "CAT_HAVE_CHILD"),
    CAT_HAVE_GOODS(-41002, "CAT_HAVE_GOODS"),
    SPEC_HAVE_GOODS(-41002, "SPEC_HAVE_GOODS"),
    SPEC_HAVE_NAME(-41003, "SPEC_HAVE_NAME"),
    SPEC_HAVE_TOO_MANY(-41004, "SPEC_HAVE_TOO_MANY"),
    GOODS_TYPE_HAVE_SPEC(-41005, "GOODS_TYPE_HAVE_SPEC"),
    GOODS_TYPE_HAVE_BRAND(-41006, "GOODS_TYPE_HAVE_BRAND"),
    GOODS_TYPE_HAVE_ATTR(-41007, "GOODS_TYPE_HAVE_ATTR"),
    GOODS_STATE_ERROR(-41008, "GOODS_STATE_ERROR"),

    VERIFY_ERROR(-60001, "VERIFY_ERROR"),
    SAME_USER_NAME(-60002, "SAME_USER_NAME"),

    ACTIVITY_CANNOT_BE_DELETED(-60100, "ACTIVITY_CANNOT_BE_DELETED"),
    ADVANCE_ACTIVITY_STOCK_ERROR(-60101, "ADVANCE_ACTIVITY_STOCK_ERROR"),
    ADVANCE_ACTIVITY_PAY_TIME_FIRST_ERROR(-60102, "ADVANCE_ACTIVITY_PAY_TIME_FIRST_ERROR"),
    ADVANCE_ACTIVITY_PAY_TIME_SECOND_ERROR(-60103, "ADVANCE_ACTIVITY_PAY_TIME_SECOND_ERROR"),
    GROUPBUY_ACTIVITY_CANNOT_ADD_FIRST(-60104, "GROUPBUY_ACTIVITY_CANNOT_ADD_FIRST"),
    GROUPBUY_ACTIVITY_CANNOT_ADD_SECOND(-60105, "GROUPBUY_ACTIVITY_CANNOT_ADD_SECOND"),
    STORE_WITHDRAWALS_MONEY(-60106, "STORE_WITHDRAWALS_MONEY"),
    SELLER_LOGIN_ERROR(-60107, "SELLER_LOGIN_ERROR"),
    DELETE_GOOD_HAVE_ORDER(-60108, "DELETE_GOOD_HAVE_ORDER"),
    PWD_LENGTH_ERROR(-60109, "PWD_LENGTH_ERROR"),
    SELLER_NAME_EXISTS(-60110, "SELLER_NAME_EXISTS"),
    STORE_EXISTS(-60111, "STORE_EXISTS"),
    ADDRESS_ERROR(-60112, "ADDRESS_ERROR"),
    SUBDOMAINS_ERROR(-60112, "SUBDOMAINS_ERROR"),
    SUBDOMAINS_EQUALS_DOMAIN(-60113, "SUBDOMAINS_EQUALS_DOMAIN"),
    SUBDOMAINS_EXISTS(-60114, "SUBDOMAINS_EXISTS"),
    STORE_GOODS_EXISTS(-60115, "STORE_GOODS_EXISTS"),
    BASIC_STORE_CANNOT_REMOVE(-60116, "BASIC_STORE_CANNOT_REMOVE"),
    CANNOT_REMOVE_STORECLASS(-60117, "CANNOT_REMOVE_STORECLASS"),
    STORE_NAME_NULL(-60118, "STORE_NAME_NULL"),
    APPLY_ACCOUNT_NOT_EXISTS(-60119, "APPLY_ACCOUNT_NOT_EXISTS"),
    STORE_CLASS_EXISTS(-60120, "STORE_CLASS_EXISTS"),
    DEFAULT_STORE_EXISTS(-60121, "DEFAULT_STORE_EXISTS"),
    GRADE_HAS_STORE(-60122, "GRADE_HAS_STORE"),
    STORE_GRADE_EXISTS(-60123, "STORE_GRADE_EXISTS"),
    APPLY_UNFINISHED(-60124, "APPLY_UNFINISHED"),
    CAN_NOT_REPEATED_CHANGES_STATE(-60125, "CAN_NOT_REPEATED_CHANGES_STATE"),
    CAN_NOT_REPEATED_CHANGES_SWITCH(-60126, "CAN_NOT_REPEATED_CHANGES_SWITCH"),
    IN_REVIEW(-60127, "IN_REVIEW"),
    SAME_SELLER_NAME(-60128, "SAME_SELLER_NAME"),
    USER_NOT_EXISTS(-60129, "USER_NOT_EXISTS"),
    USER_PWD_ERROR(-60130, "USER_PWD_ERROR"),
    USER_PWD_NOT_SAME(-60131, "USER_PWD_NOT_SAME"),
    SELLER_USER_EXISTS(-60132, "SELLER_USER_EXISTS"),
    TEAM_HAVE_FOUND_ORDER(-60133, "TEAM_HAVE_FOUND_ORDER"),

    NOT_CONFIGURED_WX(-70001, "NOT_CONFIGURED_WX"),
    FIRST_MENU_MAX_3(-70002, "FIRST_MENU_MAX_3"),
    CHILDREN_MENU_MAX_5(-70003, "CHILDREN_MENU_MAX_5"),
    NOT_MENU_PUSH(-70004, "NOT_MENU_PUSH"),
    WX_USER_NOT_EXISTS(-70005, "WX_USER_NOT_EXISTS"),
    UPDATING_TOKEN(-70006, "UPDATING_TOKEN"),
    RESPONSE_EMPTY(-70007, "RESPONSE_EMPTY"),
    WX_WAITING_ACCESS(-70008, "WX_WAITING_ACCESS"),
    USING_BY_AUTO_REPLY(-70009, "USING_BY_AUTO_REPLY"),
    VIDEO_MATERIAL_PARAMS_ERROR(-70010, "VIDEO_MATERIAL_PARAMS_ERROR"),
    GET_VIDEO_SCREENSHOT_ERROR(-70011, "GET_VIDEO_SCREENSHOT_ERROR"),
    SEND_NO_TIME(-70012,"SEND_NO_TIME"),
    FAIL_TO_SEND(-70013,"FAIL_TO_SEND")

    ;

    private Integer code;//错误码

    private String msg;//错误信息

    ResultEnum(Integer code, String msg) {
        this.code = code;
        this.msg = msg;
    }

    public Integer getCode() {
        return code;
    }

    public String getMsg() {
        return messageSource.getMessage(msg,null, msg, LocaleContextHolder.getLocale());
    }

    private MessageSource messageSource;

    public ResultEnum setMessageSource(MessageSource messageSource) {
        this.messageSource = messageSource;
        return this;
    }

    //通过静态内部类的方式注入bean，并赋值到枚举中
    @Component
    public static class ReportTypeServiceInjector {

        @Autowired
        private MessageSource messageSource;

        @PostConstruct
        public void postConstruct() {
            for (ResultEnum rt : EnumSet.allOf(ResultEnum.class))
                rt.setMessageSource(messageSource);
        }
    }

}
